In [24]:
df_final.to_csv("../data/processed/cobertura_vacinal_por_uf.csv", index=False, encoding="utf-8")
df_brasil.to_csv("../data/processed/cobertura_vacinal_brasil.csv", index=False, encoding="utf-8")
print("Arquivos atualizados com sucesso!")

Arquivos atualizados com sucesso!

In [21]:
df_final.to_csv("../data/processed/cobertura_vacinal_por_uf.csv", index=False, encoding="utf-8")
df_brasil.to_csv("../data/processed/cobertura_vacinal_brasil.csv", index=False, encoding="utf-8")

print("Arquivos salvos com sucesso!")

Arquivos salvos com sucesso!

In [6]:
df_poliomielite = tratar_vacina("../data/raw/poliomielite.csv", "Poliomielite")
df_triplice_viral = tratar_vacina("../data/raw/triplice_viral.csv", "Tríplice viral")
df_pentavalente = tratar_vacina("../data/raw/Pentavalente .csv", "Pentavalente")

# Junta as 4 vacinas num único DataFrame
df_final = pd.concat([df_bcg, df_poliomielite, df_triplice_viral, df_pentavalente], ignore_index=True)

print(df_final.shape)
df_final.head(10)

(1120, 5)

  codigo_uf         uf   ano  cobertura vacina
0        11   Rondônia  2013     108.15    BCG
1        12       Acre  2013     106.16    BCG
2        13   Amazonas  2013     116.92    BCG
3        14    Roraima  2013      94.17    BCG
4        15       Pará  2013     117.68    BCG
5        16      Amapá  2013     117.07    BCG
6        17  Tocantins  2013      92.02    BCG
7        21   Maranhão  2013     113.39    BCG
8        22      Piauí  2013      96.50    BCG
9        23      Ceará  2013     108.63    BCG

In [1]:
import pandas as pd

def tratar_vacina(caminho_arquivo, nome_vacina):
    df = pd.read_csv(caminho_arquivo, encoding="latin1", sep=";")
    
    # Remove espaços extras de TODOS os nomes de coluna (resolve o problema do " Total")
    df.columns = df.columns.str.strip()
    
    # Remove a coluna Total, se existir
    if "Total" in df.columns:
        df = df.drop(columns=["Total"])
    
    # Separa código e nome da UF
    df[["codigo_uf", "uf"]] = df["Unidade da Federação"].str.split(n=1, expand=True)
    df = df.drop(columns=["Unidade da Federação"])
    
    # Identifica quais colunas são anos (só dígitos)
    anos = [col for col in df.columns if col.strip().isdigit()]
    
    # Transforma de formato largo pra longo
    df_long = df.melt(
        id_vars=["codigo_uf", "uf"],
        value_vars=anos,
        var_name="ano",
        value_name="cobertura"
    )
    
    # Converte cobertura de texto (vírgula) pra número (ponto)
    df_long["cobertura"] = (
        df_long["cobertura"]
        .astype(str)
        .str.replace(",", ".")
        .astype(float)
    )
    
    df_long["ano"] = df_long["ano"].astype(int)
    df_long["vacina"] = nome_vacina
    
    return df_long

df_bcg = tratar_vacina("../data/raw/bcg.csv", "BCG")
df_bcg.head(10)

  codigo_uf         uf   ano  cobertura vacina
0        11   Rondônia  2013     108.15    BCG
1        12       Acre  2013     106.16    BCG
2        13   Amazonas  2013     116.92    BCG
3        14    Roraima  2013      94.17    BCG
4        15       Pará  2013     117.68    BCG
5        16      Amapá  2013     117.07    BCG
6        17  Tocantins  2013      92.02    BCG
7        21   Maranhão  2013     113.39    BCG
8        22      Piauí  2013      96.50    BCG
9        23      Ceará  2013     108.63    BCG